version: "3.9"

services:
  incident-escalation-api:
    build: .
    container_name: incident-escalation-api
    ports:
      - "7134:7134"
    env_file:
      - .env
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
