namespace: gpsd

replicaCount: 1

image:
  repository: gpsd/gpsd-escalation-mgmt
  tag: v0.0.9
  pullPolicy: Always

service:
  - name: http
    type: ClusterIP
    port: 7134
    targetPort: 7134

env:
  ESCALATION_MGMT_ENV: "TEST"
  ESCALATION_MGMT_APP_PORT: "7134"
  VAULT_ADDR: "http://vault.vault.svc.cluster.local:8200"
  VAULT_AUTH_METHOD: "kubernetes"
  VAULT_ROLE: "gpsd-escalation-mgmt"
  REDIS_PORT: "6379"
  PREDICTHQ_SEARCH_URL: "https://api.predicthq.com/v1/events/"

serviceAccount:
  create: true
  name: gpsd-escalation-mgmt-sa

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
